apiVersion: v1
kind: Service
metadata:
  name: {{ include "sidecarloggingweatherapi.fullname" . }}
  labels:
    {{- include "sidecarloggingweatherapi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sidecarloggingweatherapi.selectorLabels" . | nindent 4 }}
